# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: minimal-jekyll-theme
permalink: /:title/
title: "Shayan's Blog"
email: "sixtysix(in NUMbers)+Shayan+@+Gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  I am Shayan Tawabi and I talk about Marketing, Tech and Business
  here... Let's Connect on Social ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://66shayan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author      : Shayan Tawabi
twitter_username: ShayanTawabi
github_username:  66shayan
date_format : "%-d %b %Y"
port        : 5000

################################
# Theme Settings
################################
collections:
  docs:
    output: true
    permalink: /:collection/:path/
    
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

# Include/Exclude filetypes
include:
  - _pages

#exclude:
 # - Gemfile
 # - Gemfile.lock
  
# Navigation Menus
header_navigation:

  - title: Home
    url: /

  - title: Blog
    url: /archive/
    
  - title: About
    url: /about/

  - title: Contact
    url: mailto:xhayan@gmail.com

footer_navigation:
  - title: Privacy
    url: /privacy/

  - title: Terms
    url: /terms/

# UI Default Text
text:
  updated           : Updated          # Post updated text
  less_than         : Less than        # Post read time less than 1 minute
  minute_read       : min read         # Post read time
  words_per_minute  : 200              # Reading speed
  undefined_wpm     : Undefined parameter text.words_per_minute in your config.yml file
  caption           : Image	           # Header image caption
  post_heading      : Latest Posts     # Latest posts heading
  post_limit        : 5                # Show this many latest post on your homepage
  blog_limit	      : 10               # Show this many post on the blog
  read_more         : Read more        # Read more link
  blog_title        : All Posts        # Archives link title
  blog_url          : /archive/           # Archive link url for home.html and 404 page layouts
  copyright         : 2021	           # The from year in the copyright. The current year is updated automatically.

# UI Default Settings
author_bio          : true             # Show author bio
post_meta           : true             # Show post meta
share_icons         : true             # Show post social sharing icons
category_tag_list   : true             # Show post categories & tags
twitter_icon        : true             # Show Twitter share button
facebook_icon       : true             # Show Facebook share button
google_plus_icon    : true             # Show Google+ share button

# Markdown Settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: 66shayan

# Theme Attribution Link (Optional)
# Setting this to false will remove the attribution link from the themes footer.
attribution: true 

################################
# Analytics Settings
################################
google_tag_manager: GTM-522C3GR


################################
# Jekyll Plugins
################################
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jemoji
  - jekyll-include-cache
  - jekyll-gist

# Jekyll SEO Tag Settings https://github.com/jekyll/jekyll-seo-tag
social:
  name: Shayan Tawabi
  links:
    - https://twitter.com/ShayanTawabi
    - https://instagram.com/66shayan
    - https://www.facebook.com/ShayanTawabi

twitter:
  username: ShayanTawabi

facebook:
  app_id:
  publisher:
  admins:

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:

# Jekyll Feed Settings https://github.com/jekyll/jekyll-feed
atom_feed:
    path: # Leave blank to use default (feed.xml)

# Jekyll Archives Settings https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
     - categories
     - tags
     - year
     - month
     - day
     
layout: 'archive'
permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
    #-----------
    - name: Jekyll Deploy Action
  uses: jeffreytse/jekyll-deploy-action@v0.3.1
    #----------
